### PR TITLE
Temp table ids for large number of identifiers

### LINKED ISSUE #3: Fails when running with large number of exposures/outcomes
When running with many thousands of cohorts the SQL IN query in `inst/sql/sql_server/Scc.sql` fails. To resolve this I have created an associated PR that places the ids in temporary tables.

### PR DESCRIPTION
**Pull request by azimov**
closes #3 .

### CODE REVIEW

File: R/SelfControlledCohort.R [hunk 1]
```diff
@@ -223,6 +223,9 @@ runSelfControlledCohort <- function(connectionDetails,
     conn <- connectionDetails$conn
   }
 
+  DatabaseConnector::insertTable(conn, "tempdb..#scc_outcome_ids", data.frame(outcome_id = outcomeIds), tempTable = TRUE)
```
Comment (schuemie) [inline R/SelfControlledCohort.R]: This will not port across database platforms. I recommend using `tableName = "#scc_outcome_ids"`.

Also note that our code style guide [recommends using named arguments](https://ohdsi.github.io/Hades/codeStyle.html#Use_named_arguments). It is very easy to make a mistake if you don't!

File: inst/sql/sql_server/Scc.sql [hunk 2]
```diff
@@ -103,14 +103,14 @@ FROM (
...
+			SELECT et.@exposure_person_id AS person_id,
+				et.@exposure_id AS exposure_id,
+				et.@exposure_start_date AS exposure_start_date,
+				et.@exposure_end_date AS exposure_end_date
+				{@first_exposure_only} ? {,ROW_NUMBER() OVER (PARTITION BY et.@exposure_person_id, et.@exposure_id ORDER BY et.@exposure_start_date) AS rn1}
 			FROM
-				@exposure_database_schema.@exposure_table
-{@exposure_ids != ''} ? {			WHERE @exposure_id IN (@exposure_ids)}
+				@exposure_database_schema.@exposure_table et
+{@exposure_ids != ''} ? {			INNER JOIN tempdb..#scc_exposure_ids sei ON sei.exposure_id = et.@exposure_id }
```
Comment (schuemie) [inline inst/sql/sql_server/Scc.sql]: Same here. Will not port across database platforms. Use

```sql
INNER JOIN #scc_exposure_ids sei ON sei.exposure_id = et.@exposure_id 
```

File: inst/sql/sql_server/Scc.sql [hunk 3]
```diff
@@ -181,13 +181,13 @@ INNER JOIN (
...
-			{@first_outcome_only} ? {,ROW_NUMBER() OVER (PARTITION BY @outcome_person_id, @outcome_id ORDER BY @outcome_start_date) AS rn1}
+		SELECT ot.@outcome_person_id AS person_id,
+			ot.@outcome_id AS outcome_id,
+			ot.@outcome_start_date AS outcome_date
+			{@first_outcome_only} ? {,ROW_NUMBER() OVER (PARTITION BY ot.@outcome_person_id, ot.@outcome_id ORDER BY ot.@outcome_start_date) AS rn1}
 		FROM
-			@outcome_database_schema.@outcome_table
-{@outcome_ids != ''} ? {		WHERE @outcome_id IN (@outcome_ids)}
+			@outcome_database_schema.@outcome_table ot
+{@outcome_ids != ''} ? {		INNER JOIN tempdb..#scc_outcome_ids soi ON soi.outcome_id = ot.@outcome_id}
```
Comment (schuemie) [inline inst/sql/sql_server/Scc.sql]: Same

**Comment by schuemie** [comment]
Would you mind fixing the indicated non-compatibility issues?

**Review by schuemie — APPROVED** [review]
